### PR TITLE
Prepare for v1.0 release

### PR DESCRIPTION
**Pull request by bcorrie**
Our target is to a version 1 specification ready for approval at the AIRR Meeting in Porto in June.

### CODE REVIEW

**Comment by bcorrie** [comment]
@ajrocha @schristley do you have any thoughts or feedback on this? At the last CRWG meeting this was approved in principal. 

You can view the API in the swagger editor here: https://editor.swagger.io/?raw=https://raw.githubusercontent.com/airr-community/airr-standards/master/specs/adc-api-openapi3.yaml

There are two fundamental ADC endpoints:

- /adc-registry/info - the normal info stuff for ADC APIs
- /adc-recgistry/repositories - which returns an array, each element containing a minimal set of information about each repository. The fundamental basis is that the end user can then query each repository's /airr/v1/info endpoint to get more information.

There is also a:

- /ga4gh/service-info entry point

This implements the GA4GH Service Info entry point so the service can be "discovered" through GA4GH as per "Provides a simple standardised protocol to describe information about a single web service"
https://www.ga4gh.org/product/service-info/

I think it might be useful to also implement:

- /ga4gh/service-registry entry point

This would implement the GA4GH Service Registry interface, which "Facilitates service discovery by collecting multiple web services into groups" - https://www.ga4gh.org/product/service-registry/

This later one is not in the spec and is likely more work and may not be feasible for June.

Great to get feedback/comments.

**Comment by bcorrie** [comment]
It is a registry, so there are no queries, just simple get endpoints that return basic information.

**Comment by schristley** [comment]
Minor points...

- The contact info and email is for AIRR CRWG. I would suggest it just be AIRR-C like in the other specs.
- The only difference between `info_object` and `repository_info_object` seems to be `license` versus `data_license`. Is that distinction important in this case? Can they just be the same?
- You could technically point to the InfoObject in the AIRR spec or the ADC API instead of redefining them.
- I would suggest `url` in `repository_object` be required.
- `repository_object` has `repository` and `api`. How does that work? Does the registry call each repository /info dynamically and return those? Or are they hard-code in the registry database?
- I suppose there will be documentation and/or procedure to add new entries. The easiest thing is maybe the README just says submit an issue...

Final auxiliary question. Is the registry considered a single central one? If I run one at VDJServer am I violating something? Running a mirror site is okay, maybe desirable?

**Comment by bcorrie** [comment]
> Minor points...
> 
> * The contact info and email is for AIRR CRWG. I would suggest it just be AIRR-C like in the other specs.

I am not sure I agree with that. Since this is a registry, in my mind the contact email should be the email to use to ask questions about the registry and in particular the email to use for governance around being added to the registry. Although that governance piece is a separate topic, in the end the email in the Info block should be the email where the end user can ask about governance of the registry.

> * The only difference between `info_object` and `repository_info_object` seems to be `license` versus `data_license`. Is that distinction important in this case? Can they just be the same?

Yes probably, as long as they are referring to the same thing. I would prefer data_licence as that is the intent of the licence. In this case the Info block for the API is saying that the data extracted from the registry is under the data_licence.

Similarly, for each repository if possible, the registry should report the data_licence that the repository uses. I could actually be convince that this be dropped completely since it should be provided by the repository itself and is an opportunity for data inconsistency between the registry and repository itself.

Would be good to get feeback on that.

> * You could technically point to the InfoObject in the AIRR spec or the ADC API instead of redefining them.

Totally different topic, but I am a bit unclear around where the different licenses listed in the ADC API spec came from and what exactly they apply to. That is why I explicitly used something similar but not the same. I might create a separate issue to address that 8-)

> * I would suggest `url` in `repository_object` be required.

Agree - any others that you can think of? I started to think about that, but didn't get there...

> * `repository_object` has `repository` and `api`. How does that work? Does the registry call each repository /info dynamically and return those? Or are they hard-code in the registry database?

The idea is that `repository` describes information about the provider of the repository. The `api` provides information about the API implemented by that repository.

How they are populated and managed over time is an "implementation detail" 8-) Seriously, it is a separate issue. Of course there should be a strong mapping (identity?) between what the repository returns in its Info endpoint and what is in the registry. Where and how that is managed is not yet clear, but I suspect the de-facto ground truth is that the two should match and if they don't something is wrong somewhere.
 
> * I suppose there will be documentation and/or procedure to add new entries. The easiest thing is maybe the README just says submit an issue...

Yes, we are talking about governance of the registry and how people might submit requests to add a repository as a separate topic in CRWG. We are thinking of a mechanism similar to how the Software WG qualifies software as being AIRR compliant.

> Final auxiliary question. Is the registry considered a single central one? If I run one at VDJServer am I violating something? Running a mirror site is okay, maybe desirable?

CRWG is also discussing how to implement/deliver such a service. I definitely think that the AIRR Community should run a service itself (e.g. adc-registry.airr-community.org), but it doesn't really make sense to rely on one. Having mirrors makes sense, but we probably want some governance around that for "official mirrors". Some sort of request/approval process so the AIRR Community knows about official mirrors and official mirrors have an AIRR stamp of approval. We can then run checks to make sure the official mirrors are in sync.

So are you offering to run a mirror? Offering to run the main registry maybe? 8-)

**Comment by schristley** [comment]
> Totally different topic, but I am a bit unclear around where the different licenses listed in the ADC API spec came from and what exactly they apply to. That is why I explicitly used something similar but not the same. I might create a separate issue to address that 8-)

I have my view on what is what, but I'm sure as soon as I express it then somebody will have a different opinion. There is this [issue](https://github.com/airr-community/airr-standards/issues/203). Data licenses probably need to be on the data themselves (e.g. in the Study object?) as it might be unlikely that the same license applies to all. But at the same time, a data repository may add additional license conditions. In essence, there are numerous combinations and we'd need to think about them all for the ADC.

For the ADC registry, I think there could be a simple license like CC0 or such that applies to both the API service and the data it provides.

**Comment by schristley** [comment]
> So are you offering to run a mirror? Offering to run the main registry maybe? 8-)

Either or. I already have something similar in the [VDJServer API](https://bitbucket.org/vdjserver/vdjserver-web-api/src/c9b2817505f1ea545964e29191539792c476b7f0/swagger/vdjserver-api.yaml#lines-1232), so I'd be happy to put that source code into a standalone service. It would be javascript though ;-D

I do agree that the main registry should be under the airr-community.org domain, so as long as there isn't an issue with routing requests to VDJServer/TACC, then we can host. Though we still need a mirror because as you saw last week, sometimes TACC has major outages that leaves things in limbo for a few days.

**Comment by bussec** [comment]
> > Totally different topic, but I am a bit unclear around where the different licenses listed in the ADC API spec came from and what exactly they apply to. That is why I explicitly used something similar but not the same. I might create a separate issue to address that 8-)
> 
> I have my view on what is what, but I'm sure as soon as I express it then somebody will have a different opinion. There is this [issue](https://github.com/airr-community/airr-standards/issues/203). Data licenses probably need to be on the data themselves (e.g. in the Study object?) as it might be unlikely that the same license applies to all. But at the same time, a data repository may add additional license conditions. In essence, there are numerous combinations and we'd need to think about them all for the ADC.
> 
> For the ADC registry, I think there could be a simple license like CC0 or such that applies to both the API service and the data it provides.

@schristley It is not clear to me what you mean with the license for the API service. Is this really a "license" or more a "terms of service" (e.g., "Your are not allowed to use this service if you are reselling it to third parties"). Or you trying to cover the case in which a repository is re-licensing data sets (e.g., using a CC-BY NC instead of the CC-BY of the original authors)?

**Comment by schristley** [comment]
> @schristley It is not clear to me what you mean with the license for the API service. Is this really a "license" or more a "terms of service" (e.g., "Your are not allowed to use this service if you are reselling it to third parties"). Or you trying to cover the case in which a repository is re-licensing data sets (e.g., using a CC-BY NC instead of the CC-BY of the original authors)?

Yes, you can think of it as a "terms of service" which is a form of license that covers multiple topics. It is possible that license covers a re-licensing of the data sets and/or stating that each data set has its own license, or it might include additional disclaimers like don't sue us if the original authors snuck in PHI. As it is the single point of contact between the user and service, it's the place to add all that legalese if necessary.

**Comment by bcorrie** [comment]
> * The contact info and email is for AIRR CRWG. I would suggest it just be AIRR-C like in the other specs.

Left as is - since this is the AIRR registry, specific to the ADC, I think this should come to the CRWG.

> * The only difference between `info_object` and `repository_info_object` seems to be `license` versus `data_license`. Is that distinction important in this case? Can they just be the same?

Changed, are now the same.

> * You could technically point to the InfoObject in the AIRR spec or the ADC API instead of redefining them.

Left as is, as the descriptions are specific to the type of objects the info is attached to as documentation.

> * I would suggest `url` in `repository_object` be required.

Done, made a few other required as well (version of the ADC API and contact email for the repository).

> * `repository_object` has `repository` and `api`. How does that work? Does the registry call each repository /info dynamically and return those? Or are they hard-code in the registry database?

`repository` describes the repository itself (e.g. VDJServer, iReceptor Turnkey, DKFZ repository) while API describes the ADC API implementation of the repository.

> * I suppose there will be documentation and/or procedure to add new entries. The easiest thing is maybe the README just says submit an issue...

Yes, see #4

**Comment by bcorrie** [comment]
Going to merge this - can open another issue if we want to make more changes.

**Pull request merged**
